### PR TITLE
new 0.4 release

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like you are seeing this issue ( https://github.com/conda/conda/issues/3004 ). Let's see what they do to fix it.

**Comment by almarklein** [comment]
Had some trouble w.r.t. the installing of a resource file. This now works, except in circleci.

@jakirkham or @ivoflipse any idea why circleci would now allow the downloading of a file?

```
+ python setup.py install --single-version-externally-managed --record=record.txt
Downloading http://raw.githubusercontent.com/zoofIO/phosphor-all/2db421f7c2d60b/phosphor-all.js
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    get_all_resources()
  File "setup.py", line 92, in get_all_resources
    get_resoure_filename(name)
  File "flexx/util/getresource.py", line 56, in get_resoure_filename
    data = _fetch_file(url)
  File "flexx/util/getresource.py", line 81, in _fetch_file
    'connection? If there is, please report this problem.' % url)
IOError: Unable to download u'http://raw.githubusercontent.com/zoofIO/phosphor-all/2db421f7c2d60b/phosphor-all.js'. Perhaps there is a no internet connection? If there is, please report this problem.
```

**Comment by almarklein** [comment]
Update: it works fine if I use the zip from pypi (because it includes the resource file). This solves my problem, but still would like to know what's up with circleci ...

**Comment by Korijn** [comment]
@almarklein have you tried restarting the circleci build? It looks like it might have been an intermittent failure.

Edit: SSL failures! I missed that. You are using an HTTP url instead of HTTPS, which is unsafe.

**Comment by almarklein** [comment]
Thanks!

**Pull request merged**
